services:
  database:
    image: mariadb:11
    container_name: fieldnotes_database
    restart: unless-stopped
    
    env_file:
      - .env
    ports:
    - "3307:3306"
    volumes:
      - fieldnotes_db_data:/var/lib/mysql

volumes:
  fieldnotes_db_data: